theme: jekyll-theme-midnight

#remote_theme: daviddarnes/alembic@main

title: Digimaker CMF

description: A Progressive Content Management Framework


site:
 github:
  repository_url: https://github.com/digimakergo/digimaker
